GET http://localhost:8080/demo/all
Accept: */*
Cache-Control: no-cache

<> 2019-02-04T110738.200.txt
<> 2019-02-04T110716.200.txt
<> 2019-02-04T110352.200.txt
<> 2019-02-04T110126.200.txt
<> 2019-02-04T105841.200.txt
<> 2019-02-04T105716.404.json

###

POST http://localhost:8080/demo/add
Content-Type: application/json

{
  "name": "First",
  "email": "someemail@someemailprovider.com"
}

###

POST http://localhost:8080/demo/add
Content-Type: application/json

{
  "name": "Second",
  "email": ""
}

###


